[package]
name = "cli-calc"
version = "0.1.0"
authors = ["Juan Camilo SÃ¡nchez Urrego <jcsu2019369@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
